org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

loom_version_manifests=https://bmclapi2.bangbang93.com/mc/game/version_manifest.json
loom_experimental_versions=https://maven.fabricmc.net/net/minecraft/experimental_versions.json

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

mod_version=1.0.0
maven_group=com.cheattoggle

fabric_api_version=0.155.2+26.2
java_release=26
java_version_min=26
